python demo/demo_hqsam_auto_instances.py \
--checkpoint train/pretrained_checkpoint/sam_vit_l_0b3195.pth \
--restore-model train/work_dirs/train_hq_sam_l_100_instance-200images-3/epoch_45.pth \
--model-type vit_l \
--input images \
--output test/test_results_64_iou0.6_stable0.925_minmask1000_minarea2000_vit_l \
--device cuda \
--points-per-side 64 \
--pred-iou-thresh 0.6 \
--stability-score-thresh 0.925 \
--min-mask-region-area 100 \
--min-instance-area 2000