python demo/demo_hqsam_auto_instances.py \
--checkpoint train/pretrained_checkpoint/sam_vit_l_0b3195.pth \
--restore-model train/ckpts/vit_l_loss.pth \
--model-type vit_l \
--input "$HOME/Datasets/fiber_new/STD-04 1-1" \
--output "$HOME/Datasets/fiber_new/STD-04 1-1" \
--device cuda \
--points-per-side 64 \
--pred-iou-thresh 0.6 \
--stability-score-thresh 0.925 \
--min-hole-region-area 100 \
--min-island-region-area 3000 \
--min-instance-area 2000 \
--max-instance-area-ratio 0.1 \
--overlap-thresh 0.2 \
--resume-index 0
